### ISSUE TITLE
Support fined-grained access control in SecurityPolicy 

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2250]
## Relates to
https://github.com/envoyproxy/gateway/issues/1845

## What is this?
EG can leverage [RBAC](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/rbac) for implementing fine-grained access control, at both the `Gateway` and `xRoute` level.

The principal, obtained through the authentication process (such as OIDC, JWT, etc.), serves as the basis for defining access control policies.  Source IP-based access control can also be supported in this model.

The below is roughly how API will look like, but it's just an initial idea and definitely needs more input.
## API outline

```yaml
kind: SecurityPolicy
metadata:
  name: rbac-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: http-route
  jwt:   # a jwt or oidc configuration is needed to obtain the principal
  ......  
  authorization:
  - principals: ["john"]
    permissions:
      methods: ["GET", "POST"]
      paths: ["/foo", "/bar"]

```
Reference:https://github.com/envoyproxy/envoy/issues/7913

- [x] [Allow/Deny IP Subnets](https://github.com/envoyproxy/gateway/issues/2462)
- [x] [Authorization based on JWT claim ](https://github.com/envoyproxy/gateway/issues/3367)
- [ ] [Authorization based on Basic Auth Username](https://github.com/envoyproxy/gateway/issues/3624) https://github.com/envoyproxy/gateway/issues/2947
- [ ] Authorization based on client cert
- [ ] Authorization based on identity extracted from an arbitrary HTTP header

**Comment by arkodg** [comment]
@zhaohuabing 
* can't the `paths` and `methods` be limited by the `HTTPRoute` match fields ?
* can't the `principal` be limited by the `issuer` field in JWT https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#jwtprovider ?

**Comment by zhaohuabing** [comment]
> @zhaohuabing
> 
> * can't the `paths` and `methods` be limited by the `HTTPRoute` match fields ?

I would suggest not to go this route because:
* It could get tricky, especially when the policy targets a gateway.  
* Separate of concerns:  `SecurityPolicy`  and `HTTPRoute` may be created by different roles, such as app developers and administrators

> * can't the `principal` be limited by the `issuer` field in JWT https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#jwtprovider ?

You mean `sub`  field?

**Comment by zetaab** [comment]
@zhaohuabing if you use api outline that is mentioned in first post, it does not support "action" mentioned in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#config-rbac-v3-rbac

so instead the api spec should be something like

```
kind: SecurityPolicy
metadata:
  name: rbac-example
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: http-route
  jwt:   # a jwt or oidc configuration is needed to obtain the principal
  ......  
  authorization:
  - action: ALLOW
    policies:
    - principals:
      - <array of https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-policy >
      permissions:
      - <array of https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-permission >
      condition: # is this needed?
```

**Comment by arkodg** [comment]
@zetaab this feature has not been built out yet, you can use the existing fields in `jwt` for authz
 https://gateway.envoyproxy.io/latest/api/extension_types/#jwtprovider

**Comment by zetaab** [comment]
@arkodg yep, but just wanted to mention that there can be multiple types of "action". So perhaps worth of including that as well.

Anyways I am really waiting for this feature, so just wanted to participate

**Comment by zetaab** [comment]
@arkodg my use case is 1) I would like to have OIDC authentication (+JWT verify needed in envoy level?) 2) I would like to define that group X,Y,Z is allowed to HTTPRoute or even in global level. Currently the claims can be included in http response towards upstream afaik. However, there is no way to block requests based on the claim values.

**Comment by arkodg** [comment]
thanks for sharing your use case @zetaab 

1. To only allow specific `claims`, we can include this field within `jwt` within `SecurityPolicy`
2. To only allow specific ip addresses, we can include a `ipAllowList` / `ipDenyList`  within `ClientTrafficPolicy` / `SecurityPolicy`

both these APIs will translate intent into envoy rbac filter

**Comment by arkodg** [comment]
@guydc brought the use case of wanting to limit supported methods (send `401` status to unsupported http methods)
so it sounds like a top level `authorization` or `acl` field makes sense here which allows the user to create `ALLOW` / `DENY` `rules` with different types (`method`, `claim`, `remoteCIDR`)

**Comment by zhaohuabing** [comment]
Thanks for the great feedback! I've created an API draft based on our discussion. Please check it out and leave your thoughts.

https://github.com/envoyproxy/gateway/pull/3138
