### ISSUE TITLE
Logical optimization of provider kubernetes

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#920]
I have forked the latest code on github, I will use my experience to solve this problem...

**Problems:**
- It is uncontrollable that all relevant resources are processed in the **Reconcile** function.
  1.   #789 
- No split resource processing logic, update of endpoints is **difficult to implement**, Blocking to  implement the slowStart、lbPolicy feature
  1.    #35
  2.   #787

The root cause is that the SDK provided by the controller-runtime is not suitable for complex K8S controller projects, It is terrible logic to use a **Single Reconcile** for multiple resources. The logic is bloated and difficult to handle.

**Todo List:**
- [ ] Replace Single Reconcile And Dynamic client , Use Informer event-handler 
    - [ ] Different resources,  different work queues 
    - [ ] Split processing logic （EDS、CDS、RDS、LDS、VHDS、HDS）, Solve repeated processing  
    - [ ] Use lister cache instead of remote request 
- [ ] Support EDS, K8S endpoints update And resovle service to endpoints （**easy to  implement**）
- [ ] Support K8S Event Record  
- [ ] Support more data validation #854 
- [ ] Use proto message Equal to skip duplicate  data

**Reference :**
- [K8S Deployment Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go)
- [Istio Endpoints Informer](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/endpoints.go)

**Comment by youngnick** [comment]
Thanks for this issue, @zhshw.

The maintainers of this project have all built different Kubernetes controllers before, so I think that you're missing some context here.

The single reconciler pattern is _very_ important for a complex, interrelated set of resources like Gateway API, as changes in one resource can mean that other resources also need to be reprocessed. Doing this with separate reconcilers actually creates lots of individual reconcile events (it's quite common for a Route update to require a Gateway re-reconcile, which can then trigger re-reconciles for other Route objects, for example).

We actually did start out with separate reconcilers, but have ended up folding them back into one because of issues like this.

I agree that speeding up endpoint reconciliation is an important goal for operating EG at scale, but to this point, we have been concentrating on getting the basic functionality working, rather than scale testing. If you have numbers about scale testing you can share, that would be excellent, and a great place to start this conversation.

Finally, I guess you didn't intend this, but the way that this issue is written, it is implying something like "the current maintainers are all stupid, we should do this the _right_ way". As I said earlier, all the maintainers have built controllers before, and are solving the problems that they have had before. If you've had a different experience, that's valuable information, but an approach centered around asking _why_ things are the way they are _first_ might be better received in the future.

**Comment by arkodg** [comment]
adding to what @youngnick said, here's a GH issue that introduced merging controllers https://github.com/envoyproxy/gateway/issues/413 which has more info on the _WHY_

**Comment by zhshw** [comment]
@youngnick 
Referring to other envoy controller plane projects, none of them adopts **Single Reconcile** 

Review all commit recoder, which appear in the first commit .The building was skewed from the beginning,  and the rear maintainers are forced to use this method to deal with it.  At this time, someone must stand up and point out the problem, and can also respond to the problem through case.

Everyone here has many years of K8S development experience，*controller-runtime is not suitable for complex K8S controller*

If the scale verification design is not carried out, it is equivalent to building a high platform with floating sand.
